[tool.poetry]
name = "indexclient"
version = "2.3.0"
description = "Data-indexing and tracking client"
authors = ["CTDS UChicago <cdis@uchicago.edu>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/uc-cdis/indexclient"
include = [
  "NOTICE",
]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
requests = ">=2.5.2,<3.0.0"
cdisutilstest = {git = "https://github.com/uc-cdis/cdisutils-test.git", rev = "1.0.0"}
indexd = {git = "https://github.com/uc-cdis/indexd.git", rev = "5.0.3"}

[tool.poetry.group.dev.dependencies]
mock = "*"
pytest = "*"
pytest-cov = "^2.5.1"
cdisutilstest = {git = "https://github.com/uc-cdis/cdisutils-test.git", rev = "1.0.0"}
indexd = {git = "https://github.com/uc-cdis/indexd.git", rev = "5.0.3"}

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
